### ISSUE TITLE
Measures are displaying with a lot of decimal places

### ISSUE THREAD

**Issue by NHAnagha** [deldersveld/rDataTable#5]
After setting number of decimal to 1 or even changing the data type to whole number the measures are coming up with 7 to 8 decimal places in rDataTable.

**Comment by deldersveld** [comment]
Logged this question for MS on their GitHub repo. https://github.com/Microsoft/PowerBI-visuals/issues/313

With regular TypeScript visuals, there is a library that allows us to obtain the Format info from the data model. Not aware of anything similar for R visuals, but I've asked the question.

**Comment by deldersveld** [comment]
Added Format property to limit the number of decimal places. Not currently able to obtain the user-specified decimal digits at the field level in R visuals, so this option will affect all decimal fields in the table universally. It does not "force" decimals for whole numbers. Applied to version 1.1.0.3, and I'll resubmit it to AppSource for approval.

**Comment by NHAnagha** [comment]
Thanks a Lot!!! This really helps.
